export const product = {
  productName: "Placeholder Product",
  productType: "Bread",
  batchNumber: "12345",
  manufacturingDate: "2024-01-01",
  expiryDate: "2025-01-01",
  quantityProduced: 1000,
  description: "This is a placeholder description of the product.",
  source: "Placeholder Source",
  ingredients: "Flour, Water, Yeast",
  treatmentMethods: "Filtration, UV treatment",
  packagingType: "Plastic Bag",
  packagingDate: "2024-01-02",
  storageRequirements: "Store in a cool, dry place",
  specialInstructions: "Handle with care",
  rawMaterialSource: "Placeholder Raw Material Source",
  rawMaterialType: "Organic",
  supplierInfo: "Supplier XYZ, Address, Contact",
  procurementDate: "2023-12-01",
  quantityProcured: 500,
  additionalInfo: "This is some additional placeholder information.",
};

export const order = {
  orderNumber: "ORD12345",
  customerName: "John Doe",
  productType: "Bread",
  quantityOrdered: 200,
  batchNumber: "BATCH123",
  orderDate: "2024-01-01",
  deliveryDate: "2024-01-05",
  transportationDetails: "Delivered via truck",
  storageConditions: "Store in a cool, dry place",
  receiptDate: "2024-01-06",
  transferDate: "2024-01-07",
  additionalInfo: "Handle with care during transfer.",
};
export const orders = [
  {
    orderNumber: "ORD001",
    customerName: "Alice Johnson",
    batchNumber: "BATCH001",
    orderDate: "2024-06-01",
    deliveryDate: "2024-06-05",
    orderedQuantity: "150",
    id: "1",
  },
  {
    orderNumber: "ORD002",
    customerName: "Bob Smith",
    batchNumber: "BATCH002",
    orderDate: "2024-06-02",
    deliveryDate: "2024-06-06",
    orderedQuantity: "200",
    id: "2",
  },
  {
    orderNumber: "ORD003",
    customerName: "Catherine Lee",
    batchNumber: "BATCH003",
    orderDate: "2024-06-03",
    deliveryDate: "2024-06-07",
    orderedQuantity: "250",
    id: "3",
  },
  {
    orderNumber: "ORD004",
    customerName: "David Brown",
    batchNumber: "BATCH004",
    orderDate: "2024-06-04",
    deliveryDate: "2024-06-08",
    orderedQuantity: "300",
    id: "4",
  },
  {
    orderNumber: "ORD005",
    customerName: "Emma Wilson",
    batchNumber: "BATCH005",
    orderDate: "2024-06-05",
    deliveryDate: "2024-06-09",
    orderedQuantity: "350",
    id: "5",
  },
];

export const inventory = [
  {
    id: "1",
    productName: "Bread",
    productType: "Food",
    quantityInStock: 100,
    stockingDate: "2024-06-01",
    storageDetails: "Store in a cool, dry place",
    displayInformation: "Display at eye level",
    saleDate: "2024-06-05",
    customerName: "John Doe",
    customerContact: "1234567890",
    additionalInfo: "Handle with care",
  },
  // Add more items as needed
];
